### ISSUE TITLE
confirm e2e evaluation of rep_lang interpreter on raspberry pi

### ISSUE THREAD

**Issue by mhuesch** [neighbour-hoods/rep_interchange#2]
creating this issue to track the topic.

I believe I just succeeded in building and running the project on my Pi. I only ran `npm run test`, but I think that spins up a Holochain conductor:

```
rpi :: ~/projects/rep_interchange ‹main› » g rev-parse HEAD                                 101 ↵
23a2bc0f3a1708f05811f27ca3f741521d3b83f7
rpi :: ~/projects/rep_interchange ‹main› » npm run build

> scaffolding@1.0.0 build /home/mhueschen/projects/rep_interchange
> CARGO_TARGET_DIR=target cargo build --release --target wasm32-unknown-unknown && scripts/package-dnas.sh

    Finished release [optimized] target(s) in 1.24s
Compiling DNA in happs/scaffolding
Wrote bundle /home/mhueschen/projects/rep_interchange/happs/scaffolding/rep_dsl_test_dna.dna
    packing succeeded.

rpi :: ~/projects/rep_interchange ‹main› » npm install  
npm WARN scaffolding@1.0.0 No repository field.

up to date in 0.89s
found 0 vulnerabilities

rpi :: ~/projects/rep_interchange ‹main› » npm run test

> scaffolding@1.0.0 test /home/mhueschen/projects/rep_interchange
> cd test && npm test


> holo-dsl-scaffolding-test@0.0.1 test /home/mhueschen/projects/rep_interchange/test
> WASM_LOG=debug RUST_LOG=error RUST_BACKTRACE=1 tape test_*.js | faucet

(node:13441) ExperimentalWarning: The ESM module loader is experimental.
✓ Basic DSL program compilation
# tests 1
# pass  1
✓ ok

```

**Comment by pospi** [comment]
Neat! Can confirm- this means Holochain 0.0.102 runs on rPi! :partying_face:

**Comment by mhuesch** [comment]
@pospi can we leave this open until a full e2e run with `rep_lang`'s interpreter is successfully carried out? what was my original intent.

**Comment by mhuesch** [comment]
practically speaking, this probably depends on #3 and it would be sufficient to take the codebase as of the merging of #3's PR and confirm it works on rpi.

**Comment by mhuesch** [comment]
## notes for the future

it would be nice to keep tabs on our `aarch64` compatibility going forwards, so we can keep the door to mobile deployments open.

it was/is pretty tedious to verify this on my `rpi`. it took literal days to compile the whole Holochain toolchain (largely `llvm` I think. Holochain doesn't seem to have `aarch64` target binaries in their binary cache :thinking:). I didn't have to actively monitor, but had to check on compilation progress (and put ice packs on it to keep it from overheating :laughing:).

it's possible that there are cloud hosts which rent out beefier machines and are still semi-affordable. then we'd be able to run builds in CI on `aarch64`. and perhaps even populate a `nix` binary cache with build outputs. that would allow users to add the cache and stream prebuilt binaries to mobile devices.

this is all further future and semi-speculative, but I think we're interested in that for NH's future.

**Comment by mhuesch** [comment]
the demo asciicast is in the PR, but linking it here too: https://asciinema.org/a/vRaEh4GeSvhVGNaqbu4lQwnUV
